server:
  port: 80

spring:
  application:
    name: cloud-consumer-order80
  zipkin:
    base-url: http://47.107.47.215:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # false 表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索实例
    fetch-registry: true
    service-url:
      # 设置与Eureka Server交互的地址、查询服务和注册服务都需要依赖这个地址
     # defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-consumer-oreder80
    prefer-ip-address: true #显示ip地址