server:
  port: 80

spring:
  application:
    name: cloud-consumerconsul-order80
  cloud:
    consul:
      host: 192.168.233.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        instance-id: ${spring.application.name}