server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    # 关闭Eureka自我保护机制，保证服务不可用时被及时的剔除
    enable-self-preservation: false
    # 默认间隔时间
    eviction-interval-timer-in-ms: 2000