server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.47.215:8848

service-url:
  nacos-user-service: http://nacos-payment-provider